name: XLSX to SVG

on:
  push:
    branches:
      - main
    paths:
      - 'src/assets_book/*.xlsx'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install csvkit
        run: pip install csvkit

      - name: Setup Typst
        uses: typst/setup-action@v1
        with:
          version: v0.6.0

      - name: Find new XLSX files
        id: find_new_xlsx
        run: |
          git diff --name-only --diff-filter=A HEAD^ HEAD > new_files.txt
          grep 'src/assets_book/table-id-.*\.xlsx' new_files.txt > xlsx_files.txt || true
          cat xlsx_files.txt

      - name: Process new XLSX files
        run: |
          while IFS= read -r xlsx_file; do
            if [ -z "$xlsx_file" ]; then
              continue
            fi
            base_name=$(basename "$xlsx_file" .xlsx)
            number=$(echo "$base_name" | sed 's/table-id-//')
            csv_file="src/assets_book/${base_name}.csv"
            typ_file="src/assets_book/${base_name}.typ"
            svg_file="src/assets_book/${base_name}.svg"
            md_file="src/idea/ch${number}.md"

            # Convert .xlsx to .csv
            in2csv "$xlsx_file" > "$csv_file"

            # Create .typ file from template
            sed "s/table-id-1.csv/${base_name}.csv/g" src/assets_book/table-id-1.typ | sed "s/table-id-1/${base_name}/g" > "$typ_file"

            # Compile .typ to .svg
            typst compile "$typ_file" "$svg_file"

            # Append SVG to markdown file
            echo "" >> "$md_file"
            echo "![${base_name}](../assets_book/${base_name}.svg)" >> "$md_file"
          done < xlsx_files.txt

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/assets_book/*.csv src/assets_book/*.typ src/assets_book/*.svg src/idea/*.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated: Generate assets from XLSX"
          git push